=== HIT-Go-Forward/Online-Course-Sharing-Platform/target/classes/common/dtd/server-config.dtd
<!ELEMENT server (media-server?, mail?)>

<!ELEMENT media-server (address)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT port (#PCDATA)>

<!ELEMENT mail (account, password, auth-code, smtp-host, templates?)>
<!ELEMENT account (#PCDATA)>
<!ELEMENT password (#PCDATA)>
<!ELEMENT auth-code (#PCDATA)>
<!ELEMENT smtp-host (#PCDATA)>
<!ELEMENT templates (template*)>
<!ELEMENT template (key, value)>
<!ELEMENT key (#PCDATA)>
<!ELEMENT value (#PCDATA)>

=== HIT-Go-Forward/Online-Course-Sharing-Platform/target/to-go-server/WEB-INF/classes/server-config.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE server SYSTEM 'common/dtd/server-config.dtd'>
<server>
    <media-server>
        <address>http://47.94.148.40:8080/media-server</address>
        <port>8080</port>
    </media-server>

    <mail>
        <account>15846376962@163.com</account>
        <password>cfmy0714..</password>
        <auth-code>byq0714</auth-code>
        <smtp-host>smtp.163.com</smtp-host>
        <templates>
            <template>
                <key>validateCodeMail</key>
                <value>
                    您此次操作的验证码是 {validateCode},15分钟内有效.
                    注意信息安全, 请勿透露给他人!
                    祝您生活愉快~
                    --Hit-Go-Forward团队
                </value>
            </template>
        </templates>
    </mail>
</server>
